import "./globals.css";

// local font import
import LocalFont from "next/font/local";

// remote font import
import { Bebas_Neue } from "next/font/google";
import Header from "@/components/header";

// remote font kurulumu
const bebas = Bebas_Neue({
  subsets: ["latin"],
  variable: "--font-bebas",
  weight: ["400"],
});

// local font kurulum
const superMindset = LocalFont({
  src: "../assets/super.ttf",
  variable: "--font-super",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`h-full antialiased ${bebas.variable} ${superMindset.variable}`}>
      <body className={`min-h-full flex flex-col text-2xl`}>
        <Header />

        <main className="p-10">{children}</main>
      </body>
    </html>
  );
}
