const ACTION_TYPES = {
  REST_LOADING: "REST_LOADING",
  REST_ERROR: "REST_ERROR",
  REST_SUCCESS: "REST_SUCCESS",

  CART_LOADING: "CART_LOADING",
  CART_ERROR: "CART_ERROR",
  CART_SUCCESS: "CART_SUCCESS",
};

export default ACTION_TYPES;
